#!/bin/bash

complete -W "install uninstall config sandbox spawnpoints spawnregions checkmods maxmen adminpasswd userpasswd status console log clearbackups clearzpop start restart cancelrestart stop quit kill command cmd message msg" pzserver
