#!/bin/bash

. "$(dirname "${0}")/pzenv"

check_is_pzserver_user

if ! [ -f "${JAVAMODSCONSOLE}" ]; then
	echo No log file found for this user.
	exit
fi

FULL="${1}"
if [ "${FULL}" = "--full" ]; then
	AMOUNT=+1
else
	AMOUNT=-1000
fi

tail -f -n "${AMOUNT}" "${JAVAMODSCONSOLE}"
