#!/bin/bash
set -e

. "$(dirname "${0}")/pzenv"

check_is_pzserver_user

TMP=$(mktemp)
wget -q -O "${TMP}" "${JAVAMODSURL}"
unzip -o -qq -d "${PZSERVER}" "${TMP}"
rm -f "${TMP}"

"${PZSERVER}/jre64/bin/java" -jar "${PZSERVER}/java/javamods.jar"

echo OK
