#!/bin/bash

. "$(dirname "${0}")/pzenv"

if ! [ -f "${RESTARTJOBPATH}" ]; then
	echo No restart job running
	exit
fi

rm -f "${RESTARTJOBPATH}"

if [ -z "$(get_pz_pid)" ]; then
	echo OK
	exit
fi

pzmessage "Server restart was canceled by operator"
