#!/bin/bash

. "$(dirname "${0}")/pzenv"

if ! [ -f "${RESTARTJOBPATH}" ]; then
	echo No restart job running
	exit
fi

rm -f "${RESTARTJOBPATH}"

pzmessage "Server restart has been canceled by operator"
