#!/bin/bash

. "$(dirname "${0}")/pzenv"

install_steamcmd

"${STEAM}/steamcmd.sh" +force_install_dir "${HOME}/pzserver/" +login anonymous +app_update 380870 b41multiplayer validate +quit

pzst_config --add

echo OK
