#!/bin/bash

. "$(dirname "${0}")/pzenv"

install_steamcmd

"${STEAM}/steamcmd.sh" +force_install_dir "${HOME}/pzserver/" +login anonymous +app_update 380870 b41multiplayer validate +quit

pzst_config --add

mkdir -p "${HOME}/Zomboid/mods"

# Prevent exit from hiding the exit status code of ProjectZomboid process
sed -i '/^exit 0$/d' "${PZSERVERSTART}"

echo OK
