#!/bin/bash

. "$(dirname "${0}")/pzenv"

APPID='380870'
if ! [ -z "${1}" ]; then
	APPID="${1}"
fi

install_steamcmd

"${STEAM}/steamcmd.sh" +force_install_dir "${HOME}/pzserver/" +login anonymous +app_update "${APPID}" b41multiplayer validate +quit

pzst_config --add

if ! [ -z "${MAXMEM}" ]; then
	pzmaxmem "${MAXMEM}" > /dev/null
fi

mkdir -p "${LOCALCRONDIR}"
cp "${LIB}/cron/pzserver" "${LOCALCRONDIR}"
cat "${LOCALCRONDIR}/"* | crontab -

# Create missing folder to avoid java exception
mkdir -p "${HOME}/Zomboid/mods"

# Prevent exit from hiding the exit status code of ProjectZomboid process
sed -i '/^exit 0$/d' "${PZSERVERSTART}"

echo OK
