#!/etc/pzst/env/bin/python

import os
import sys
import json

from os.path import isfile


if len(sys.argv) < 2:
	print('Usage: %s <gigabytes>' % sys.argv[0])
	sys.exit()

gigabytes = int(sys.argv[1])

user = os.getenv('USER')

configpath = '/home/%s/.pzst/config.json' % user
if isfile(configpath):
	with open(configpath, 'r') as fd:
		config = json.loads(fd.read())
		config['maxmem'] = gigabytes
	with open(configpath, 'w') as fd:
		fd.write(json.dumps(config, indent='\t'))

success = False

for arch in [ 32, 64 ]:

	filepath = '/home/%s/pzserver/ProjectZomboid%d.json' % (user, arch)
	if not isfile(filepath):
		continue

	with open(filepath) as fd:
		jsondata = json.loads(fd.read())

	for index, option in enumerate(jsondata['vmArgs']):
		if option.startswith('-Xmx'):
			jsondata['vmArgs'][index] = '-Xmx%dg' % gigabytes

	with open(filepath, 'w') as fd:
		fd.write(json.dumps(jsondata, indent='\t') + os.linesep)

	success = True

if success:
	print('OK')

else:
	print('No pzserver available for user %s' % user)
