#!/bin/bash

. "$(dirname "${0}")/pzenv"

USERS=($(jq -r -c 'try .pzservers[]' "${CONFIG}"))
if [ -z "${USERS}" ]; then
	echo No pzserver configured
	exit
fi

STATUS='No pzserver to restart'
for USER in ${USERS[@]}; do

	# Don't use RESTARTSWITCH from pzenv because
	# this it's run as a cron job as pzst user
	RESTARTSWITCH="${CACHEDIR}/restart.${USER}"

	if [ -f "${RESTARTSWITCH}" ]; then
		pzrestartjob "${USER}" > /dev/null &
		STATUS='OK'
	fi

done

echo "${STATUS}"
