#!/bin/bash

. "$(dirname "${0}")/pzenv"

USERS=($(jq -r -c 'try .pzservers[]' "${CONFIG}"))
if [ -z "${USERS}" ]; then
	echo No pzserver configured
	exit
fi

for USER in ${USERS[@]}; do
	detach pzrestartjob "${USER}" $@ > /dev/null &
done

echo OK
