#!/bin/bash

BASE="$(dirname "${0}")"

usage() {
	echo "Usage: ${0} <command> [args]..."
	echo
	echo Available commands:
	echo
	echo '  install        Install or update pzserver'
	echo '  uninstall      Uninstall pzserver'
	echo '  deletepz       Delete Project Zomboid'
	echo
	echo '  config         Edit pzserver configuration (servertest.ini)'
	echo '  sandbox        Edit pzserver sandbox settings'
	echo '  spawnpoints    Edit pzserver spawn points'
	echo '  spawnregions   Edit pzserver spawn regions'
	echo '  checkmods      Check mod updates'
	echo '  maxmen         Change pzserver maximum memory allocation'
	echo
	echo '  userpasswd     Change pzserver user password'
	echo '  status         Check pzserver status'
	echo '  console        Show pzserver console output'
	echo '  linkmaps       Create symlinks for map mods'
	echo '  backupsave     Perform a backup of the current save'
	echo '  clearzpop      Clear zombie population'
	echo '  kickall        Kill all connected players'
	echo
	echo '  start          Start pzserver in the background'
	echo '  restart        Restart pzserver'
	echo '  cancelrestart  Cancel restart job'
	echo '  stop           Stop pzserver'
	echo '  kill           Kill pzserver (unclean shutdown)'
	echo
	echo '  command        Run a server command (additem, chopper, etc)'
	echo '  message        Display custom message in-game'
	echo
	exit
}

COMMAND="${1}"
if [ -z "${COMMAND}" ]; then
	usage
fi

shift

case "${COMMAND}" in

	install)
		"${BASE}/pzinstall" $@
		;;

	uninstall)
		"${BASE}/pzuninstall" $@
		;;

	deletepz)
		"${BASE}/pzdeletepz" $@
		;;

	config)
		"${BASE}/pzconfig" $@
		;;

	sandbox)
		"${BASE}/pzsandbox" $@
		;;

	spawnpoints)
		"${BASE}/pzspawnpoints" $@
		;;

	spawnregions)
		"${BASE}/pzspawnregions" $@
		;;

	checkmods)
		"${BASE}/pzcheckmods" $@
		;;

	maxmen)
		"${BASE}/pzmaxmem" $@
		;;

	userpasswd)
		"${BASE}/pzuserpasswd" $@
		;;

	status)
		"${BASE}/pzstatus" $@
		;;

	console|log)
		"${BASE}/pzconsole" $@
		;;

	linkmaps)
		"${BASE}/pzlinkmaps" $@
		;;

	backupsave)
		"${BASE}/pzbackupsave" $@
		;;

	clearzpop)
		"${BASE}/pzclearzpop" $@
		;;

	kickall)
		"${BASE}/pzkickall" $@
		;;

	start)
		"${BASE}/pzstart" $@
		;;

	restart)
		"${BASE}/pzrestart" $@
		;;

	cancelrestart)
		"${BASE}/pzcancelrestart" $@
		;;

	stop|quit)
		"${BASE}/pzstop" $@
		;;

	kill)
		"${BASE}/pzkill" $@
		;;

	command|cmd)
		"${BASE}/pzcommand" $@
		;;

	message|msg)
		"${BASE}/pzmessage" $@
		;;

	*)
		echo Unknown command ${COMMAND}
		echo
		usage
		;;
esac
