#!/bin/bash

. "$(dirname "${0}")/pzenv"

check_is_pzserver_user

if ! [ -d "${PZSERVERDIR}" ] || ! [ -f "${PZSERVERSPAWNPOINTS}" ]; then
	echo Configuration not found
	exit
fi

"${EDITOR}" "${PZSERVERSPAWNPOINTS}"
