#!/bin/bash

. "$(dirname "${0}")/pzenv"

check_is_pzserver_user

check_not_running

check_first_time

detach "$(dirname "${0}")/pzstartloop" ${ADMINUSEROPTION} ${ADMINPASSWDOPTION} ${@} &

sleep 0.5

if [ -z "$(jobs -r)" ]; then
	echo pzserver already running

else
	echo OK
fi
