#!/bin/bash

. "$(dirname "${0}")/pzenv"

check_is_pzserver_user

flock -n "${PZSERVERLOCK}" echo > /dev/null
if [ "${?}" = '0' ] && [ -z "$(get_pz_pid)" ]; then
	echo Status: Not running

else
	echo Status: Running
fi
