#!/bin/bash

. "$(dirname "${0}")/pzenv"

check_is_pzserver_user

check_not_running

while true; do

	rm -f "${KILLSWITCH}"

	[[ -f "${PZSERVERLOG}" ]] && cp "${PZSERVERLOG}" "${PZSERVERLOG}.old"

	"${PZSERVERSTART}" ${@} &> /dev/null

	#if [ -d "${PZSERVERSAVE}" ]; then
	#	mkdir -p "${PZSERVERBACKUP}"
	#	cp -a "${PZSERVERSAVE}" "${PZSERVERBACKUP}/$(date +%Y%m%d-%H%M%S)"
	#fi

	if [ -f "${KILLSWITCH}" ]; then
		echo Kill switch detected, quitting.
		rm -f "${KILLSWITCH}"
		break
	fi

	echo Restarting.
done
