#!/bin/bash

. "$(dirname "${0}")/pzenv"

TMP=$(mktemp)

usage() {
	rm -f "${TMP}"
	echo "Usage ${0} [--add|--del|--admin <username>|--install <path>|--port <port>]"
	exit
}

if [ -z "${1}" ]; then
	usage
fi

if ! [ -f "${LOCALCONFIG}" ] && [ "${USER}" != 'pzst' ]; then
	mkdir -p "${LOCALCONFIGDIR}"
	echo '{}' > "${LOCALCONFIG}"
fi

ARG="${1}"

if [ "${ARG}" = '-a' ] || [ "${ARG}" = '--add' ]; then

	jq --tab ".pzservers |= (. + [\"${USER}\"] | unique)" "${CONFIG}" > "${TMP}"
	cp "${TMP}" "${CONFIG}"

elif [ "${ARG}" = '-d' ] || [ "${ARG}" = '--del' ]; then

	jq --tab ".pzservers |= (. - [\"${USER}\"] | unique)" "${CONFIG}" > "${TMP}"
	cp "${TMP}" "${CONFIG}"

elif [ "${ARG}" = '-A' ] || [ "${ARG}" = '--admin' ]; then

	USERNAME="${2}"
	if [ -z "${USERNAME}" ]; then
		echo Option \`${ARG}\` requires a username
		echo
		usage
	fi

	jq --tab ".admin=\"${USERNAME}\"" "${LOCALCONFIG}" > "${TMP}"
	cp "${TMP}" "${LOCALCONFIG}"

elif [ "${ARG}" = '-i' ] || [ "${ARG}" = '--install' ]; then

	INSTALLPATH="${2}"
	if [ -z "${INSTALLPATH}" ]; then
		echo Option \`${ARG}\` requires a path
		echo
		usage
	fi

	jq --tab ".user=\"${USER}\" | .install=\"${INSTALLPATH}\"" "${CONFIG}" > "${TMP}"
	cp "${TMP}" "${CONFIG}"

elif [ "${ARG}" = '-p' ] || [ "${ARG}" = '--port' ]; then

	PORT="${2}"
	if [ -z "${PORT}" ]; then
		echo Option \`${ARG}\` requires a port number
		echo
		usage
	fi

	jq --tab ".port=${PORT}" "${LOCALCONFIG}" > "${TMP}"
	cp "${TMP}" "${LOCALCONFIG}"

else
	echo "Invalid option ${ARG}"
	echo
	usage
fi

rm -f "${TMP}"
