#!/bin/bash

. "$(dirname "${0}")/pzenv"

check_is_pzserver_user

jmuninstall > /dev/null

rm -rf "${PZSERVER}"

pzst_config --del

rm -f "${LOCALCONFIG}" "${LOCALLOG}" "${LOCALCRONDIR}/pzserver"

if [ -d "${LOCALCRONDIR}" ]; then
	rmdir "${LOCALCRONDIR}"
fi

if [ -d "${LOCALCONFIGDIR}" ]; then
	rmdir "${LOCALCONFIGDIR}"
fi

echo OK
