#!/bin/bash

. "$(dirname "${0}")/pzenv"

RESTARTS=($(jq -r -c 'try ."daily-restarts"[]' "${CONFIG}"))
if [ -z "${RESTARTS}" ]; then
	echo No daily-restart configured
	exit
fi

INDEX=$(jq -r -c "try .pzservers | index(\"${USER}\")")
if [ "${INDEX}" = 'null' ]; then
	echo No pzserver configured for user ${USER}
	exit
fi

DATE=$(date +%H:%M)
MSG="Performing daily restart (${DATE})"

for RESTART in ${RESTARTS[@]}; do

	if [ "${RESTART}" = "${DATE}" ]; then

		echo "${MSG}"                 >> "${LOCALLOG}"
		pzrestartjob "${USER}" --stop >> "${LOCALLOG}"
		echo pzrestartjob status: $?  >> "${LOCALLOG}"
		pzinstall                     >> "${LOCALLOG}"
		echo pzinstall status: $?     >> "${LOCALLOG}"
		pzstart                       >> "${LOCALLOG}"
		echo pzstart status: $?       >> "${LOCALLOG}"
	fi
done
