#!/bin/bash

# Ask for sudo password before printing anything to the console
sudo echo -n

. "$(dirname "${0}")/pzenv"

RESTARTS=($(jq -r -c 'try ."daily-restarts"[]' "${CONFIG}"))
if [ -z "${RESTARTS}" ]; then
	echo No daily-restart configured
	exit
fi

USERS=($(jq -r -c 'try .pzservers[]' "${CONFIG}"))
if [ -z "${USERS}" ]; then
	echo No pzserver configured
	exit
fi

DATE=$(date +%H:%M)

for RESTART in ${RESTARTS[@]}; do

	if [ "${RESTART}" = "${DATE}" ]; then

		for USER in ${USERS[@]}; do

			echo Updating pzservers \`${USER}\`

			sudo -u "${USER}" pzrestartjob "${USER}" --stop
			sudo -u "${USER}" pzinstall
			sudo -u "${USER}" pzstart

		done

		break
	fi
done
