#!/bin/bash

. "$(dirname "${0}")/pzenv"

ADMIN="$(jq -r 'try .admin' "${LOCALCONFIG}")"
if [ -z "${ADMIN}" ]; then
	echo This pzserver is not fully configured yet.
	echo Please run \`pz start\` before using this command.
	exit
fi

RESTARTS=($(jq -r -c 'try ."daily-restarts"[]' "${CONFIG}"))
if [ -z "${RESTARTS}" ]; then
	echo No daily-restart configured
	exit
fi

INDEX=$(jq -r -c "try .pzservers | index(\"${USER}\")" "${CONFIG}")
if [ "${INDEX}" = 'null' ]; then
	echo No pzserver configured for user ${USER}
	exit
fi

DATE=$(date +%H:%M)
MSG="Performing daily restart (${DATE})"
STATUS='No daily-restart to perform now'

for RESTART in ${RESTARTS[@]}; do

	if [ "${RESTART}" = "${DATE}" ]; then

		pzrestartjob "${USER}" --stop
		pzinstall
		pzstart
		STATUS='OK'
	fi
done

echo ${STATUS}
