#!/bin/bash
set -e

. "$(dirname "${0}")/pzenv"

VERSION=0.0.3
ARCHIVE='javamods-linux.zip'
URL="https://github.com/quarantin/javamods/releases/download/${VERSION}/${ARCHIVE}"

if ! [ -d "${PZSERVER}" ]; then
	echo No installed pzserver found
	exit
fi

TMP=$(mktemp)
wget -q -O "${TMP}" "${URL}"
unzip -o -qq -d "${PZSERVER}" "${TMP}"
rm -f "${TMP}"

TMP=$(mktemp)
jq '.javamods = true' "${LOCALCONFIG}" > "${TMP}"
mv -f "${TMP}" "${LOCALCONFIG}"

echo OK
