#!/bin/bash
set -e

. "$(dirname "${0}")/pzenv"

if ! [ -d "${PZSERVER}" ]; then
	echo No installed pzserver found
	exit
fi

rm -rf "${JAVAMODSHOME}"

git clone --quiet --depth 1 -c advice.detachedHead=false --branch "${JAVAMODSVERSION}" "${JAVAMODSURL}" "${JAVAMODSHOME}"

mkdir -p "${JAVAMODSCONFIGDIR}"
cp "${JAVAMODSHOME}/config.json" "${JAVAMODSCONFIGDIR}"

echo OK
