#!/bin/bash

. "$(dirname "${0}")/pzenv"

if ! [ -d "${PZSERVER}" ]; then
	echo No installed pzserver found
	exit
fi

rm -f \
	"${PZSERVER}/javamods.json"            \
	"${PZSERVER}/javamods-start-server.sh" \
	"${PZSERVER}/java/javamods.jar"        \
	"${JAVAMODSCONFIG}"

rmdir "${JAVAMODSCONFIGDIR}"

echo OK
