#!/bin/bash

. "$(dirname "${0}")/pzenv"

if ! [ -d "${PZSERVERBACKUP}" ]; then
	echo No backup found
	exit
fi

DAYS="$(jq '."max-backup-age" // 7' "${CONFIG}")"

STATUS="No backup older than ${DAYS} days found"
while read BACKUP; do

	STATUS='OK'
	echo Deleting backup ${BACKUP}
	rm -rf "${BACKUP}"

done < <(find "${PZSERVERBACKUP}/" -maxdepth 1 -mindepth 1 -mtime ${DAYS})

echo ${STATUS}
