#!/bin/bash

. "$(dirname "${0}")/pzenv"

if [ -z "${1}" ]; then
	echo Usage: ${0} command...
	exit
fi

PID=$(get_pz_pid)
if [ -z "${PID}" ]; then
	echo No running pzserver found
	exit
fi

if [ "${1}" == 'servermsg' ]; then
	shift
	sudo ioctl "${PID}" servermsg \"${@}\" && echo OK
else
	sudo ioctl "${PID}" ${@} && echo OK
fi
