#!/bin/bash

. "$(dirname "${0}")/pzenv"

PID=$(get_pz_pid)
if [ -z "${PID}" ]; then
	echo No running pzserver found
	exit
fi

if ! [ -e "${KILLSWITCH}" ]; then
	touch "${KILLSWITCH}"
fi

sudo ioctl "${PID}" quit

echo OK
