#!/bin/bash

. "$(dirname "${0}")/pzenv"

PIDS=($(grep -l 'ProjectZomboid\(32\|64\)' /proc/[0-9]*/cmdline | cut -f3 -d/))
if [ -z "${PIDS}" ]; then
	echo Process not found for user ${USER}
	exit
fi

if ! [ -e "${KILLSWITCH}" ]; then
	touch "${KILLSWITCH}"
fi

STATUS='No process found'
for PID in ${PIDS[@]}; do
	LINK="$(readlink "/proc/${PID}/fd/0")"
	if [ "${LINK}" != "/dev/null" ]; then
		sudo ioctl ${PID} quit
		STATUS=OK
	fi
done

echo $STATUS
