#!/bin/bash

# Ask for sudo password before printing anything to the console
sudo echo -n

. "$(dirname "${0}")/pzenv"

PID=$(get_pz_pid)
if [ -z "${PID}" ]; then
	echo No running pzserver found
	exit
fi

sudo ioctl "${PID}" quit && echo OK
