#!/bin/bash

. "$(dirname "${0}")/pzenv"

if ! [ -f "${CONFIG}" ]; then
	echo No configuration found
	echo Quitting
	exit
fi

NOW="$(date +%H:%M)"
USERS=($(jq -r -c '.pzservers[]' "${CONFIG}"))
RESTARTS=($(jq -r -c '.restarts[]' "${CONFIG}"))
if [-z "${USERS}" ] || [ -z "${RESTARTS}" ]; then
	exit
fi

for RESTART in ${RESTARTS[@]}; do

	if [ "${RESTART}" = "${NOW}" ]; then
		for USER in ${USERS[@]}; do
			pzrestart
		done
	fi

done
