#!/bin/bash

# Ask for sudo password before printing anything to the console
sudo echo -n

. "$(dirname "${0}")/pzenv"

USERS=($(jq -r -c 'try .pzservers[]' "${CONFIG}"))
if [ -z "${USERS}" ]; then
	echo No pzserver configured
	exit
fi

STATUS='No pzserver to restart'
for USER in ${USERS[@]}; do

	RESTARTSWITCH="/tmp/pzserver.${USER}.restart"
	if [ -f "${RESTARTSWITCH}" ]; then
		sudo pzrestartjob "${USER}" > /dev/null &
		STATUS='OK'
	fi

done

echo "${STATUS}"
