#!/bin/bash

. "$(dirname "${0}")/pzenv"

check_running

while true; do

	rm -f "${KILLSWITCH}" "/tmp/pzserver.${USER}.restart"

	[[ -f "${PZSERVERLOG}" ]] && cp "${PZSERVERLOG}" "${PZSERVERLOG}.old"

	"${PZLAUNCHER}" &> "${PZSERVERLOG}"

	if [ -f "${KILLSWITCH}" ]; then
		echo Kill switch detected, quitting.
		rm -f "${KILLSWITCH}" "/tmp/pzserver.${USER}.restart"
		break
	fi

	echo Restarting.
done
