#!/bin/bash

. "$(dirname "${0}")/pzenv"

check_running

while true; do

	rm -f "${KILLSWITCH}" "/tmp/pzserver.${USER}.restart"

	[[ -f "${LOGFILE}" ]] && cp "${LOGFILE}" "${LOGFILE}.old"

	"${PZLAUNCHER}" &> "${LOGFILE}"

	if [ -f "${KILLSWITCH}" ]; then
		echo Kill switch detected, quitting.
		rm -f "${KILLSWITCH}" "/tmp/pzserver.${USER}.restart"
		break
	fi

	echo Restarting.
done
