#!/bin/bash

. "$(dirname "${0}")/pzenv"

if ! [ -d "${ZOMBOIDSERVERDIR}" ] || ! [ -f "${ZOMBOIDSERVERSPAWNREGIONS}" ]; then
	echo Configuration not found.
	exit
fi

"${EDITOR}" "${ZOMBOIDSERVERSPAWNREGIONS}"
