#!/bin/bash

. "$(dirname "${0}")/pzenv"

usage() {
	echo "Usage ${0} [--add|--del]"
	exit
}

if [ -z "${1}" ]; then
	usage "${0}"
fi

ARG="${1}"
TMP=$(mktemp)

if [ "${ARG}" = '-a' ] || [ "${ARG}" = '--add' ]; then

	jq ".pzservers |= (. + [\"${USER}\"] | unique)" "${CONFIG}" > "${TMP}"
	sg pzst "cp ${TMP} ${CONFIG}"

elif [ "${ARG}" = '-d' ] || [ "${ARG}" = '--del' ]; then

	jq ".pzservers |= (. - [\"${USER}\"] | unique)" "${CONFIG}" > "${TMP}"
	sg pzst "cp ${TMP} ${CONFIG}"

else
	echo "Invalid option ${ARG}"
	echo
	usage "${0}"
fi
