#!/bin/bash

. "$(dirname "${0}")/pzenv"

TMP=$(mktemp)

usage() {
	rm -f "${TMP}"
	echo "Usage ${0} [--add|--del|--admin <username>]"
	exit
}

if [ -z "${1}" ]; then
	usage "${0}"
fi

ARG="${1}"

if [ "${ARG}" = '-a' ] || [ "${ARG}" = '--add' ]; then

	jq --tab ".pzservers |= (. + [\"${USER}\"] | unique)" "${CONFIG}" > "${TMP}"
	cp "${TMP}" "${CONFIG}"

elif [ "${ARG}" = '-d' ] || [ "${ARG}" = '--del' ]; then

	jq --tab ".pzservers |= (. - [\"${USER}\"] | unique)" "${CONFIG}" > "${TMP}"
	cp "${TMP}" "${CONFIG}"

elif [ "${ARG}" = '-A' ] || [ "${ARG}" = '--admin' ]; then

	USERNAME="${2}"
	if [ -z "${USERNAME}" ]; then
		echo Option \`${ARG}\` requires a username
		echo
		usage "${0}"
	fi

	jq --tab ".admin=\"${USERNAME}\"" "${CONFIG}" > "${TMP}"
	cp "${TMP}" "${CONFIG}"

else
	echo "Invalid option ${ARG}"
	echo
	usage "${0}"
fi

rm -f "${TMP}"

echo OK
