#!/bin/bash

. "$(dirname "${0}")/pzenv"

check_not_running

while true; do

	rm -f "${KILLSWITCH}" "${RESTARTSWITCH}"

	[[ -f "${PZSERVERLOG}" ]] && cp "${PZSERVERLOG}" "${PZSERVERLOG}.old"

	"${PZSERVERSTART}" ${@} &> /dev/null

	mkdir -p "${PZSERVERBACKUP}"
	cp -a "${PZSERVERSAVE}" "${PZSERVERBACKUP}/$(date +%Y%m%d-%H%M%S)"

	PORT="$(echo "${PORTOPTION}" | cut -f2 -d' ')"
	if ! [ -z "${PORT}" ]; then
		sed -i "s/^DefaultPort.*/DefaultPort=${PORT}/" "${PZSERVERCONFIG}"
	fi

	rm -f "${RESTARTSWITCH}"
	if [ -f "${KILLSWITCH}" ]; then
		echo Kill switch detected, quitting.
		rm -f "${KILLSWITCH}"
		break
	fi

	echo Restarting.
done
