#!/bin/bash

# Ask for sudo password before printing anything to the console
sudo echo -n

. "$(dirname "${0}")/pzenv"

USERS=($(jq -r -c 'try .pzservers[]' "${CONFIG}"))
if [ -z "${USERS}" ]; then
	echo No pzserver configured
	exit
fi

for USER in ${USERS[@]}; do

	echo Updating pzservers \`${USER}\`

	sudo -u "${USER}" pzinstall > /dev/null && sudo pzrestarterjob "${USER}" &

done

echo OK
