#!/bin/bash

# Ask for sudo password before printing anything to the console
sudo echo -n

ALLOW_ROOT='true'

. "$(dirname "${0}")/pzstenv"

echo [*] Updating Project Zomboid Server Tools

cd "${REPO}"

CURRENT_BRANCH="$(git name-rev --name-only HEAD)"

BRANCH="${CURRENT_BRANCH}"
if ! [ -z "${1}" ]; then
	BRANCH="${1}"
fi

if [ "${BRANCH}" != "${CURRENT_BRANCH}" ]; then
	sudo -u "${PZSTUSER}" git checkout --quiet "${BRANCH}"
fi

sudo -u "${PZSTUSER}" git fetch --quiet

sudo -u "${PZSTUSER}" git reset --quiet --hard "origin/${BRANCH}"

sudo -u "${PZSTUSER}" "${REPO}/pzst/pzstinstall"
