#!/bin/bash

# Ask for sudo password before printing anything to the console
sudo echo -n

. "$(dirname "${0}")/pzstenv"

SRC="${REPO}/src"

sudo rm -f "${INSTALLCHECK}"

echo [*] Deleting virtual environment

sudo rm -rf "${CONFIGENV}"

echo [*] Uninstalling Project Zomboid Server Tools

sudo rm -f "${CRONFILE}"
sudo /etc/init.d/cron restart > /dev/null

for SCRIPT in $(ls -1 "${REPO}/pzserver"); do
	sudo rm -f "${BIN}/${SCRIPT}"
done

for SCRIPT in $(ls -1 "${REPO}/pzst"); do
	sudo rm -f "${BIN}/${SCRIPT}"
done

sudo service pzstd stop 2> /dev/null
sudo systemctl disable pzstd.service 2> /dev/null
sudo rm -f /etc/systemd/system/pzstd.service

sudo make -C "${SRC}" uninstall > /dev/null

sudo rm -f "${CACHE}" "${LOCK}" "${SOCKETPATH}" "${CONFIG}" "${CRONFILE}" "${LOGFILE}"

if [ -d "${CACHEDIR}" ]; then
	sudo rmdir "${CACHEDIR}"
fi

if [ -d "${CONFIGDIR}" ]; then
	sudo rmdir "${CONFIGDIR}"
fi

echo [*] Removing system user: pzst

sudo userdel pzst 2> /dev/null || true
sudo groupdel pzst 2> /dev/null || true

echo OK
