#!/bin/bash

# Ask for sudo password before printing anything to the console
sudo echo -n

# Safety check, don't do anything if we can't find pzstenv
PZSTENV=/usr/local/bin/pzstenv
if ! [ -f "${PZSTENV}" ]; then
	echo Nothing to uninstall
	exit
fi

. "$(dirname "${0}")/pzstenv"

SRC="${REPO}/src"

echo [*] Deleting virtual environment

sudo rm -rf "${CONFIGENV}"

echo [*] Uninstalling Project Zomboid Server Tools

sudo rm -f "${CRONFILE}"
sudo /etc/init.d/cron restart > /dev/null

for SCRIPT in $(ls -1 "${REPO}/pzserver"); do
	sudo rm -f "${BIN}/${SCRIPT}"
done

for SCRIPT in $(ls -1 "${REPO}/pzst"); do
	sudo rm -f "${BIN}/${SCRIPT}"
done

sudo service pzstd stop 2> /dev/null
sudo systemctl disable pzstd.service 2> /dev/null
sudo rm -f /etc/systemd/system/pzstd.service

sudo make -C "${SRC}" uninstall > /dev/null

sudo rm -f "${CACHE}" "${LOCK}" "${SOCKETPATH}" "${CONFIG}" "${CRONFILE}" "${CONFIGDIR}/htpasswd"

if [ -d "${CACHEDIR}" ]; then
	sudo rmdir "${CACHEDIR}"
fi

if [ -d "${CONFIGDIR}" ]; then
	sudo rmdir "${CONFIGDIR}"
fi

if [ -d "${LOGDIR}" ]; then
	sudo rm -f "${LOGFILE}/*.log"
	sudo rmdir "${LOGDIR}"
fi

echo [*] Removing system user: pzst

sudo userdel pzst 2> /dev/null || true
sudo groupdel pzst 2> /dev/null || true
