#!/bin/bash

# Ask for sudo password before printing anything to the console
sudo echo -n

. "$(dirname "${0}")/pzstenv"

echo [*] Updating Project Zomboid Server Tools

cd "${REPO}"

CURRENT_BRANCH="$(git name-rev --name-only HEAD)"

BRANCH="${CURRENT_BRANCH}"
if ! [ -z "${1}" ]; then
	BRANCH="${1}"
fi

if [ "${BRANCH}" != "${CURRENT_BRANCH}" ]; then
	git checkout --quiet "${BRANCH}"
fi

git fetch --quiet

git reset --quiet --hard "origin/${BRANCH}"

"${REPO}/pzst/pzstinstall"
