#!/bin/bash

BASE="$(dirname "${0}")"

usage() {
	echo "Usage: ${0} <command>"
	echo
	echo Available commands:
	echo
	echo '  install        Install pzst'
	echo '  update         Update pzst'
	echo '  unintsall      Uninstall pzst'
	echo
	echo '  config         Edit pzst configuration'
	echo '  checkconfig    Check pzst configuration for syntax errors'
	echo '  clearbackups   Clear old backups'
	echo
	exit
}

COMMAND="${1}"
if [ -z "${COMMAND}" ]; then
	usage
fi

shift

case "${COMMAND}" in

	install)
		"${BASE}/pzstinstall" $@
		;;

	update)
		"${BASE}/pzstupdate" $@
		;;

	uninstall)
		"${BASE}/pzstuninstall" $@
		;;

	config)
		"${BASE}/pzstconfig" $@
		;;

	checkconfig)
		"${BASE}/pzstcheckconfig" $@
		;;

	clearbackups)
		"${BASE}/pzstclearbackups" $@
		;;

	*)
		echo Unknown command ${COMMAND}
		echo
		usage
		;;
esac
